title: Panduka Neluwala
logo: /assets/Pandukaneluwalaphoto.jpg
remote_theme: pages-themes/minimal@v0.2.0


  defaults:
    # _docs
    - scope:
        path: ""
        type: main
      values:
        sidebar:
          nav: "main"
